kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --remote

- name: build
  image: docker
  commands:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose -f docker-compose.yml docker-compose-staging.yml build
  when:
    branch:
    - devops

