kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

- name: build
  image: plugins/docker
  commands:
  - docker-compose -f docker-compose.yml docker-compose-staging.yml pull
  when:
    branch:
    - devops

