kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --remote

- name: build
  image: tmaier/docker-compose:latest
  commands:
    - docker-compose -f docker-compose.yml -f docker-compose-staging.yml build
  when:
    branch:
    - devops

