kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

- name: test
  image: ruby
  commands:
  - bundle install --jobs=3 --retry=3
  - rake
  when:
    branch:
    - devops