version: '3'

services:
  interface:
    container_name: interface
    build: 
      context: ./interface
      args:
        - APP_ENV=production
        - API_URL=http://curriculo.prefeitura.sp.gov.br
    environment:
        - NPM_CONFIG_LOGLEVEL=${NPM_CONFIG_LOGLEVEL}
    stdin_open: true
    tty: true
    restart: always

  api:
    container_name: api
    build: ./api
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
      - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS}
      - PUMA_PORT=${PUMA_PORT}
      - APP_PATH=${APP_PATH}
      - SECRET_KEY=${SECRET_KEY}
      - RAILS_ENV=${RAILS_ENV}
    command: puma -v -C config/puma.rb
    stdin_open: true
    tty: true
    volumes:
      - api_storage:/app/storage
    links:
      - postgresql
    depends_on:
      - postgresql
    restart: always

  postgresql:
    container_name: postgresql
    image: mdillon/postgis:10-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
      - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./conf/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    restart: always

  nginx:
      container_name: nginx
      build: 
        context: .
        dockerfile: ./conf/nginx/Dockerfile
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      command: [nginx-debug, '-g', 'daemon off;']
      depends_on:
        - api
        - interface
      links:
        - api
        - interface
      restart: always

volumes:
  postgresql_data:
  api_storage:
  
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
