version: '3'

services:
  interface:
    image: registry.curriculo.jurema.la/interface:latest
  api:
    image: registry.curriculo.jurema.la/api:latest
  nginx:
    image: registry.curriculo.jurema.la/nginx:latest
