version: '3'

services:
  interface:
    build: 
      context: ./interface
      args:
        - APP_ROOT=${APP_ROOT}
        - APP_ENV=${APP_ENV}
    container_name: interface
    working_dir: /app
    ports:
      - 5000        
    env_file: .env.interface
    stdin_open: true
    tty: true
    restart: always

  api:
    build: ./api
    working_dir: /app
    env_file:
      - ./.env.postgresql
      - ./.env.api
    command: puma -v -C config/puma.rb
    stdin_open: true
    tty: true
    volumes:
      - api_storage:/app/storage
    ports:
      - 8666
    links:
      - postgresql
    depends_on:
      - postgresql
    restart: always

  postgresql:
    image: mdillon/postgis:10-alpine
    ports:
      - 5432
    env_file: ./.env.postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./conf/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    restart: always

  nginx:
      build: 
        context: .
        dockerfile: ./conf/nginx/Dockerfile
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      command: [nginx-debug, '-g', 'daemon off;']
      depends_on:
        - api
        - interface
      links:
        - api
        - interface
      restart: always

volumes:
  postgresql_data:
  api_storage:
  
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
