version: '3'

services:

  interface:
    container_name: interface
    build: 
      context: ./interface
      args:
        - APP_ENV=production
        - API_URL=http://0.0.0.0
    networks:
      - frontend
    env_file: .env.interface
    stdin_open: true
    tty: true
    restart: always

  api:
    container_name: api
    build: ./api
    env_file:
      - ./.env.postgresql
      - ./.env.api
    stdin_open: true
    tty: true
    volumes:
      - api_storage:/app/storage
    links:
      - postgresql
      - elasticsearch
    depends_on:
      - postgresql
      - elasticsearch
    networks:
      - backend
    restart: always

  postgresql:
    container_name: postgresql
    image: mdillon/postgis:10-alpine
    ports:
      - 5432
    networks:
      - backend
    env_file: ./.env.postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./conf/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    env_file: ./.env.elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./conf/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - api
      - interface
    links:
      - api
      - interface
    restart: always

volumes:
  postgresql_data:
  api_storage:
  elasticsearch_data:

networks:
  frontend:
  backend:
