version: '3'

services:
  interface:
    build: 
      context: ${APP_ROOT}/interface
      args:
        - APP_ROOT=${APP_ROOT}
    container_name: interface
    working_dir: /app
    ports:
      - 5000:5000  
    volumes:
      - ${APP_ROOT}/interface:/app      
    env_file: ${APP_ROOT}/.env.interface
    stdin_open: true
    tty: true

  api:
    build: ${APP_ROOT}/api
    working_dir: /app
    env_file:
      - ${APP_ROOT}/.env.postgresql
      - ${APP_ROOT}/.env.api
    command: puma -v -C config/puma.rb
    stdin_open: true
    tty: true
    volumes:
      - ${APP_ROOT}/api:/app
    ports:
      - 8666:8666
    links:
      - postgresql
    depends_on:
      - postgresql

  postgresql:
    image: mdillon/postgis:10-alpine
    ports:
      - 5432:5432
    env_file: ${APP_ROOT}/.env.postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  nginx:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ${APP_ROOT}/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        - ${APP_ROOT}/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ${APP_ROOT}/api/public:/api
      command: [nginx-debug, '-g', 'daemon off;']
      depends_on:
        - api
        - interface
      links:
        - api
        - interface

volumes:
  postgresql_data: